### ISSUE TITLE
Error on vb.net file

### ISSUE THREAD

**Issue by FabArd** [yoshizow/global-pygments-plugin#16]
Hi,

I try to generate Gtags on vb.net files and I have these errors : 
$ gtags --explain
 - File 'GrblErrorsSingleton.vb' is handled as follows:
        suffix:   |.vb|
        language: |VB.net|
        parser:   |parser|
        library:  |/usr/lib/gtags/pygments-parser.so|
ctags: Unknown option: --gmap-vb
 - File 'GrblMacroButtons.vb' is handled as follows:
        suffix:   |.vb|
        language: |VB.net|
        parser:   |parser|
        library:  |/usr/lib/gtags/pygments-parser.so|
Traceback (most recent call last):
  File "/usr/share/gtags/script/pygments_parser.py", line 262, in <module>
    main()
  File "/usr/share/gtags/script/pygments_parser.py", line 259, in main
    handle_requests(langmap, parser_options)
  File "/usr/share/gtags/script/pygments_parser.py", line 221, in handle_requests
    tags = parser.parse(path)
  File "/usr/share/gtags/script/pygments_parser.py", line 177, in parse
    def_result = self.def_parser.parse(path)
  File "/usr/share/gtags/script/pygments_parser.py", line 155, in parse
    self.child_stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
gtags: unexpected EOF.

Do I make something wrong ?

Thanks

**Comment by FabArd** [comment]
I found the solution to my problem.
There was a wrong vb.ctags in my ctags config directory.
I deleted this config file and every thing is correct.
